<?php    
    //$photo = $this->basePath("assets/academe/images/default.jpg"); //default
    
    $current_position = 'Chancellor'; // get position
    $allowed_position = ['Chancellor', 'Cost Center Head', 'Human Resource Staff'];
?>

<div id="systems">
	<h4>Leave Applications</h4>
    <?php if (in_array($current_position, $allowed_position)) : ?>
        <p style="text-align:center;"><a href="#"> Leave Pending</a></p>    
    <?php else : ?>
        <p style="text-align:center;"><a href="#"> # Pending</a></p>
    <?php endif; ?>	
</div>
<div id="calendar">
<h4>Calendar</h4>
<?php // echo $this->calendar->generate(date('Y'), date('n')); ?>
</div>